fat_proc + viewer

diff --git a/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_axialize_anat b/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_axialize_anat
--- a/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_axialize_anat
+++ b/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_axialize_anat
@@ -26,8 +26,29 @@
 set version   = "2.5"
 set rev_dat   = "Jan, 2017"
 set this_prog = "fat_proc_axialize_anat"
+set here      = $PWD
 
-set here     = $PWD
+# ----------------- find AFNI and set viewer ---------------------
+
+# find AFNI binaries directory and viewer location
+set adir      = ""
+set my_viewer = ""
+which afni >& /dev/null
+if ( $status ) then
+    echo "** Cannot find 'afni' (??!?!)."
+    goto BAD_EXIT
+else
+    set aa   = `which afni`
+    set adir = $aa:h
+endif
+
+# default location of viewer: user could modify!
+#set my_viewer = "$adir/@chauffeur_afni" !!!!!!!!!!!!!!!
+set my_viewer = "$here/@chauffeur_afni"
+
+
+# ----------------------- set defaults --------------------------
+
 set anat_dir = ""                   # will be output dir
 set anat_inp = ""                   # nec input T1w vol
 set anat_ref = ""                   # optional, if SS'ing elsewhere
@@ -50,11 +71,12 @@ set valthr   = 90
 set powcon   = 1.1  # enhance contrast in t2w mode
 
 set OutMatchRef = "0"
-set output_cmd  = "1"
-set cmd_file    = "command_copy.txt"
 
-set my_viewer   = "tcsh /data/PROJECTS/FATVIEW/viewer_afni.tcsh"  # !!!!!
-set DO_VIEWER   = 1
+set DO_VIEWER   = 1                # def: do viewing
+set qc_prefix   = ""               # def: autoname; user can enter
+set output_cmd  = 1                # def: output copy of this command
+                                   # -> should expand to have all cmds
+set cmd_file    = ""               # def: same name as viewer
 
 # ------------------- process options, a la rr ----------------------
 
@@ -70,77 +92,82 @@ while ( $ac <= $#argv )
         goto SHOW_VERSION
     endif
 
-   # required
-   if ( "$argv[$ac]" == "-inset" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_inp = "$argv[$ac]"
+    # required
+    if ( "$argv[$ac]" == "-inset" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_inp = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-refset" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_ref = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-refset" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_ref = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-outdir" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_dir = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-outdir" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_dir = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-prefix" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set outpref = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-prefix" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set outpref = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-extra_al_opts" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set extra_allin_apps = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-extra_al_opts" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set extra_allin_apps = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-extra_al_inps" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set extra_allin_inps = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-extra_al_inps" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set extra_allin_inps = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-extra_al_cost" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set costfunc = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-extra_al_cost" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set costfunc = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-t2w_mode" ) then
-      set DoUni  = "0"
-      set DoAni  = "1"
-      set valthr = 99
+    else if ( "$argv[$ac]" == "-t2w_mode" ) then
+        set DoUni  = "0"
+        set DoAni  = "1"
+        set valthr = 99
 
-   else if ( "$argv[$ac]" == "-do_clean" ) then
-      set DoClean = 1
+    else if ( "$argv[$ac]" == "-do_clean" ) then
+        set DoClean = 1
+        
+    # turn it *off* if desired-- on by default
+    else if ( "$argv[$ac]" == "-no_pre_lr_symm" ) then
+        set PRE_LR = 0
 
-  # turn it *off* if desired-- on by default
-   else if ( "$argv[$ac]" == "-no_pre_lr_symm" ) then
-      set PRE_LR = 0
+    else if ( "$argv[$ac]" == "-post_lr_symm" ) then
+        set POST_LR = 1
 
-   else if ( "$argv[$ac]" == "-post_lr_symm" ) then
-      set POST_LR = 1
+    else if ( "$argv[$ac]" == "-no_cmd_out" ) then
+        set output_cmd = 0
 
-   else if ( "$argv[$ac]" == "-no_cmd_out" ) then
-      set output_cmd = "0"
+    else if ( "$argv[$ac]" == "-wdir" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set wdir = "$argv[$ac]"
+        
+    else if ( "$argv[$ac]" == "-out_match_ref" ) then
+        set OutMatchRef = 1
 
-   else if ( "$argv[$ac]" == "-wdir" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set wdir = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-no_qc_view" ) then
+        set DO_VIEWER = 0
 
-   else if ( "$argv[$ac]" == "-out_match_ref" ) then
-      set OutMatchRef = 1
+    else if ( "$argv[$ac]" == "-qc_prefix" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set qc_prefix = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-no_qc_view" ) then
-      set DO_VIEWER = 0
-
-   else
-      echo "** unexpected option #$ac = '$argv[$ac]'"
-      exit 2
-
-   endif
-   @ ac += 1
+    else
+        echo "** unexpected option #$ac = '$argv[$ac]'"
+        goto BAD_EXIT
+        
+    endif
+    @ ac += 1
 end
 
 
@@ -156,7 +183,7 @@ set check = `3dinfo "$anat_inp"`
 echo "$#check"
 if ( "$#check" == "0" ) then
     echo "** ERROR: can't find inset file $anat_inp !"
-    goto EXIT
+    goto BAD_EXIT
 endif
 
 set inp_ORIENT = `3dinfo -orient "$anat_inp"`
@@ -167,7 +194,7 @@ set inp_VIEW  = "$inp_VIEW:gas/+//"
 set check = `3dinfo "$anat_ref"`
 if ( $#check == "0" ) then
     echo "** ERROR: can't find refset file $anat_ref !"
-    goto EXIT
+    goto BAD_EXIT
 endif
 
 # ========================= output/working dir ==========================
@@ -199,9 +226,7 @@ if ( ! -e $wdir ) then
 else
     echo "+* WARNING: Somehow found a premade working directory (?):"
     echo "      $wdir"
-
 endif
-
 
 # =======================================================================
 # =========================== ** PROCESS ** =============================
@@ -211,6 +236,22 @@ echo "\n-----> STARTING ---->"
 
 echo "\n\nThis command:"
 echo "$this_prog $argv\n\n"
+
+if ( $cmd_file == "" ) then
+    set cmd_file = "imqc_axize_${outpref}.txt"
+endif
+
+# copy original command:
+# dump copy of command into workdir/..
+if ( $output_cmd == 1 ) then
+    echo "++ Echoing the command to: $cmd_file"
+
+    echo "# Executed from the directory location:"  > $cmd_file
+    echo "# $here\n"            >> $cmd_file
+    echo "# The command was:"   >> $cmd_file
+    echo "# $this_prog $argv"   >> $cmd_file
+    echo "\n"                   >> $cmd_file
+endif
 
 echo "\nThe reference template is: $anat_ref"
 
@@ -306,7 +347,6 @@ if ( $DoUni ) then
 
     echo "\n++ Doing unifizing."
 
-
     # unifize input
     set iidx = `printf "%02d" $idx`
     set fin  = "$fout"
@@ -335,10 +375,9 @@ if ( $DoUni ) then
         -prefix   "$fout"                      \
         -overwrite
     @ idx += 1
-else
 
+else
     echo "\n++ NOT doing unifizing, at user behest."
-    
 endif
 
 # --------------------------------------------------------------
@@ -410,8 +449,8 @@ endif
 
 if ( $OutMatchRef == "0" ) then
     # default
-
     echo "++ Aligning center of refset -> inset."
+
     # make data sets close together before starting to align formally;
     # rewrite REF
     @Align_Centers               \
@@ -420,7 +459,6 @@ if ( $OutMatchRef == "0" ) then
         -dset "$rout"            \
         -base "$fout"
 else
-
     echo "++ Aligning center of inset -> refset."
     @Align_Centers               \
         -cm                      \
@@ -439,16 +477,16 @@ endif
 set iidx = `printf "%02d" $idx`
 set fin  = "$fout"
 set fout = "${tpref}_${iidx}_alnd.nii.gz"
-3dAllineate   -echo_edu               \
-    -1Dparam_save _map_9dof           \
-    -warp shift_rotate_scale          \
-    -prefix "$fout"                   \
-    -base "$rout"                     \
-    -twopass                          \
-    -source_automask                  \
-    -cost $costfunc                   \
-    $extra_allin_inps                 \
-    -source "$fin" \
+3dAllineate   -echo_edu                    \
+    -1Dparam_save _map_9dof                \
+    -warp shift_rotate_scale               \
+    -prefix "$fout"                        \
+    -base "$rout"                          \
+    -twopass                               \
+    -source_automask                       \
+    -cost $costfunc                        \
+    $extra_allin_inps                      \
+    -source "$fin"                         \
     -overwrite
 @ idx += 1
 
@@ -474,7 +512,6 @@ set fout = "${tpref}_${iidx}_alnd0.nii.gz"
     $extra_allin_apps                      \
     -overwrite
 @ idx += 1
-
 
 # --------------------------------------------------------------
 
@@ -525,8 +562,8 @@ if ( $OutMatchRef == "0" ) then
     # output).
     echo "++ Setting (0, 0, 0) to the center of mass."
     3dCM -automask -set 0 0 0 $fout
-endif
 
+endif
 
 # DONE, just copy endprod out!
 set fin  = $fout
@@ -539,29 +576,23 @@ set fout = ../"${outpref}.nii.gz"
     -expr 'a'                 \
     -prefix $fout
 
-# copy original command:
-
-# dump copy of command into workdir
-if ( $output_cmd == "1" ) then
-    echo "++ Echoing the command to: $cmd_file"
-
-    echo "# Executed from the directory location:"  > $cmd_file
-    echo "$here"              >> $cmd_file
-    echo "# The command was:" >> $cmd_file
-    echo "$this_prog $argv"   >> $cmd_file
-    echo "\n"                 >> $cmd_file
-endif
-
 # ---------------------------- VIEWER ---------------------------------
 
 if ( $DO_VIEWER ) then
 
-    echo "++ Output QC #1: final olay on (essentially) original refset."
+    if( $qc_prefix == "" ) then
+        set vpref = imqc_axize_${outpref}
+    else
+        set vpref = $qc_prefix
+    endif
+    echo "++ Image prefix output: $vpref"
+
+    #echo "++ Output QC #1: final olay on (essentially) original refset."
     echo "++ HERE: $PWD"
-    $my_viewer      -ulay $inp0       \
-                    -prefix "image_final_on_ref_`3dinfo -orient $inp0`"    \
+    $my_viewer      -ulay $inp0                     \
+                    -prefix $vpref                  \
                     -outdir ".."                    \
-                    -montx 4 -monty 4               \
+                    -montx 3 -monty 3               \
                     -set_xhairs MULTI               \
                     -label_mode 1 -label_size 4
 endif
@@ -583,7 +614,7 @@ printf "\n     $PWD/$fout\n\n"
 
 cd $here
 
-goto EXIT
+goto GOOD_EXIT
 
 # ========================================================================
 # ========================================================================
@@ -751,12 +782,14 @@ cat << EOF
 -------------------------------------------------------------------------
 EOF
 
-    goto EXIT
+    goto GOOD_EXIT
 
 SHOW_VERSION:
    echo "version  $version (${rev_dat})"
-   goto EXIT
+   goto GOOD_EXIT
 
-# send everyone here, in case there is any cleanup to do
-EXIT:
-   exit
+BAD_EXIT:
+    exit 1
+
+GOOD_EXIT:
+    exit 0
