fatproc+view

diff --git a/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_t2w_from_t1w b/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_t2w_from_t1w
--- a/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_t2w_from_t1w
+++ b/src/ptaylor/FAT_PRE_SCRIPTS_JAN18/fat_proc_t2w_from_t1w
@@ -5,19 +5,47 @@
 # --------------------- revision history -------------------------
 # Jan, 2017
 #   + rename
+#
+# Jan, 2017b
+#   + drive QC snapshots
+#
+
 # ----------------------------------------------------------------
 
-set version = "2.2"
+set version = "2.3"
 set rev_dat = "Jan, 2017"
 set this_prog = "fat_proc_t2w_from_t1w"
-
 set here     = $PWD
-set anat_dir = ""                   # will be output dir
-set T1in     = ""                   # nec input T1w vol
-set T1in_ss  = ""                   # optional, if SS'ing elsewhere
-set outpref  = "out"                # for final output files
-set temppref = "_tempZ43q6"         # for intermed files
-set DoClean  = "0"
+
+# ----------------- find AFNI and set viewer ---------------------
+
+# find AFNI binaries directory and viewer location
+set adir      = ""
+set my_viewer = ""
+which afni >& /dev/null
+if ( $status ) then
+    echo "** Cannot find 'afni' (??!?!)."
+    goto BAD_EXIT
+else
+    set aa   = `which afni`
+    set adir = $aa:h
+endif
+
+# default location of viewer: user could modify!
+set my_viewer = "$adir/@chauffeur_afni"
+
+# ----------------------- set defaults --------------------------
+
+set anat_dir  = ""                # will be output dir
+set T1in      = ""                # nec input T1w vol
+set T1in_ss   = ""                # optional, if SS'ing elsewhere
+set outpref   = "t2w"             # for final output files
+set temppref  = "_tempZ43q6"      # for intermed files
+set DoClean   = "0"
+
+set qc_prefix = ""
+set DO_VIEWER = 1                 # def: do QC image visualization
+set postfix   = "irct"            # stick into name
 
 # ------------------- process options, a la rr ----------------------
 
@@ -33,36 +61,44 @@ while ( $ac <= $#argv )
         goto SHOW_VERSION
     endif
 
-   # required
-   if ( "$argv[$ac]" == "-inset" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set T1in = "$argv[$ac]"
+    # required
+    if ( "$argv[$ac]" == "-inset" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set T1in = "$argv[$ac]"
+        
+    else if ( "$argv[$ac]" == "-in_ss" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set T1in_ss = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-in_ss" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set T1in_ss = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-outdir" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_dir = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-outdir" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_dir = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-prefix" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set outpref = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-prefix" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set outpref = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-do_clean" ) then
+        set DoClean = 1
 
-   else if ( "$argv[$ac]" == "-do_clean" ) then
-      set DoClean = 1
+    else if ( "$argv[$ac]" == "-no_qc_view" ) then
+        set DO_VIEWER = 0
 
-   else
-      echo "** unexpected option #$ac = '$argv[$ac]'"
-      exit 2
+    else if ( "$argv[$ac]" == "-qc_prefix" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set qc_prefix = "$argv[$ac]"
 
-   endif
-   @ ac += 1
+    else
+        echo "** unexpected option #$ac = '$argv[$ac]'"
+        exit 2
+
+    endif
+    @ ac += 1
 end
 
 # =======================================================================
@@ -76,14 +112,14 @@ echo "++ Start script version: $version"
 set check = `3dinfo "$T1in"`
 if ( "$#check" == "0" ) then
     echo "** ERROR: can't find file $T1in !"
-    goto EXIT
+    goto BAD_EXIT
 endif
 
 if ( $T1in_ss != "" ) then
     set check = `3dinfo "$T1in_ss"`
     if ( "$#check" == "0" ) then
         echo "** ERROR: can't find file $T1in_ss !"
-        goto EXIT
+        goto BAD_EXIT
     endif
 endif
 
@@ -218,11 +254,10 @@ set fout  = "$wdir/${outpref}_t1w_ss.nii"
     -echo_edu                                     \
     -a $fin1                                      \
     -b $fin2                                      \
-    -expr "maxbelow(${P_THR},a)*(1*b)" \
+    -expr "maxbelow(${P_THR},a)*(1*b)"            \
     -prefix $fout                                 \
     -float                                        \
     -overwrite
-
 
 # try making an imitation T2
 set fin1  = "$t1out"
@@ -247,7 +282,32 @@ endif
 printf "\n DONE!\n View T1w file:\n    ${t1out}\n"
 printf "\n DONE!\n View 'T2w' file:\n    ${t2out}\n"
 
-goto EXIT
+# ---------------------------- VIEWER ---------------------------------
+
+if ( $DO_VIEWER ) then
+
+    echo "++ Making QC images."
+
+    if( $qc_prefix == "" ) then
+        set vpref1 = ${outpref}_${postfix}_qc1_fin
+    else
+        set vpref1 = ${qc_prefix}_${postfix}_qc1_fin
+    endif
+
+    echo "++ QC image #1 (final output ulay): $vpref1"
+    $my_viewer      -ulay $fout                     \
+                    -prefix $vpref1                 \
+                    -outdir "."                     \
+                    -montx 5 -monty 3               \
+                    -set_xhairs OFF                 \
+                    -label_mode 1 -label_size 3     \
+                    -globalrange ""                 \
+                    -do_clean
+endif
+
+# ---------------------------------------------------------------------
+
+goto GOOD_EXIT
 
 # ========================================================================
 # ========================================================================
@@ -337,12 +397,14 @@ cat << EOF
 
 EOF
 
-    goto EXIT
+    goto GOOD_EXIT
 
 SHOW_VERSION:
-   echo "version  $version (${rev_dat})"
-   goto EXIT
+    echo "version  $version (${rev_dat})"
+    goto GOOD_EXIT
 
-# send everyone here, in case there is any cleanup to do
-EXIT:
-   exit
+BAD_EXIT:
+    exit 1
+
+GOOD_EXIT:
+    exit 0
