fat_proc + viewer

diff --git a/src/ptaylor/FAT_PRE_SCRIPTS_JAN11/fat_proc_axialize_anat b/src/ptaylor/FAT_PRE_SCRIPTS_JAN11/fat_proc_axialize_anat
--- a/src/ptaylor/FAT_PRE_SCRIPTS_JAN11/fat_proc_axialize_anat
+++ b/src/ptaylor/FAT_PRE_SCRIPTS_JAN11/fat_proc_axialize_anat
@@ -17,13 +17,38 @@
 #
 # Jan, 2017
 #   + rename
+#
+# Jan, 2017b
+#   + put in viewing stuff
+#
 # ----------------------------------------------------------------
 
 set version   = "2.5"
 set rev_dat   = "Jan, 2017"
 set this_prog = "fat_proc_axialize_anat"
+set here      = $PWD
 
-set here     = $PWD
+# ----------------- find AFNI and set viewer ---------------------
+
+# find AFNI binaries directory and viewer location
+set adir      = ""
+set my_viewer = ""
+which afni >& /dev/null
+if ( $status ) then
+    echo "** Cannot find 'afni' (??!?!)."
+    goto BAD_EXIT
+else
+    set aa   = `which afni`
+    set adir = $aa:h
+endif
+
+# default location of viewer: user could modify!
+#set my_viewer = "$adir/@chauffeur_afni" !!!!!!!!!!!!!!!
+set my_viewer = "$here/@chauffeur_afni"
+
+
+# ----------------------- set defaults --------------------------
+
 set anat_dir = ""                   # will be output dir
 set anat_inp = ""                   # nec input T1w vol
 set anat_ref = ""                   # optional, if SS'ing elsewhere
@@ -46,8 +71,12 @@ set valthr   = 90
 set powcon   = 1.1  # enhance contrast in t2w mode
 
 set OutMatchRef = "0"
-set output_cmd  = "1"
-set cmd_file    = "command_copy.txt"
+
+set DO_VIEWER   = 1                # def: do viewing
+set qc_prefix   = ""               # def: autoname; user can enter
+set output_cmd  = 1                # def: output copy of this command
+                                   # -> should expand to have all cmds
+set cmd_file    = ""               # def: same name as viewer
 
 # ------------------- process options, a la rr ----------------------
 
@@ -63,74 +92,82 @@ while ( $ac <= $#argv )
         goto SHOW_VERSION
     endif
 
-   # required
-   if ( "$argv[$ac]" == "-inset" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_inp = "$argv[$ac]"
+    # required
+    if ( "$argv[$ac]" == "-inset" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_inp = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-refset" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_ref = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-refset" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_ref = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-outdir" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set anat_dir = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-outdir" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set anat_dir = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-prefix" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set outpref = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-prefix" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set outpref = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-extra_al_opts" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set extra_allin_apps = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-extra_al_opts" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set extra_allin_apps = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-extra_al_inps" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set extra_allin_inps = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-extra_al_inps" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set extra_allin_inps = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-extra_al_cost" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set costfunc = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-extra_al_cost" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set costfunc = "$argv[$ac]"
 
-   else if ( "$argv[$ac]" == "-t2w_mode" ) then
-      set DoUni  = "0"
-      set DoAni  = "1"
-      set valthr = 99
+    else if ( "$argv[$ac]" == "-t2w_mode" ) then
+        set DoUni  = "0"
+        set DoAni  = "1"
+        set valthr = 99
 
-   else if ( "$argv[$ac]" == "-do_clean" ) then
-      set DoClean = 1
+    else if ( "$argv[$ac]" == "-do_clean" ) then
+        set DoClean = 1
+        
+    # turn it *off* if desired-- on by default
+    else if ( "$argv[$ac]" == "-no_pre_lr_symm" ) then
+        set PRE_LR = 0
 
-  # turn it *off* if desired-- on by default
-   else if ( "$argv[$ac]" == "-no_pre_lr_symm" ) then
-      set PRE_LR = 0
+    else if ( "$argv[$ac]" == "-post_lr_symm" ) then
+        set POST_LR = 1
 
-   else if ( "$argv[$ac]" == "-post_lr_symm" ) then
-      set POST_LR = 1
+    else if ( "$argv[$ac]" == "-no_cmd_out" ) then
+        set output_cmd = 0
 
-   else if ( "$argv[$ac]" == "-no_cmd_out" ) then
-      set output_cmd = "0"
+    else if ( "$argv[$ac]" == "-wdir" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set wdir = "$argv[$ac]"
+        
+    else if ( "$argv[$ac]" == "-out_match_ref" ) then
+        set OutMatchRef = 1
 
-   else if ( "$argv[$ac]" == "-wdir" ) then
-      if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
-      @ ac += 1
-      set wdir = "$argv[$ac]"
+    else if ( "$argv[$ac]" == "-no_qc_view" ) then
+        set DO_VIEWER = 0
 
-   else if ( "$argv[$ac]" == "-out_match_ref" ) then
-      set OutMatchRef = 1
+    else if ( "$argv[$ac]" == "-qc_prefix" ) then
+        if ( $ac >= $#argv ) goto FAIL_MISSING_ARG
+        @ ac += 1
+        set qc_prefix = "$argv[$ac]"
 
-   else
-      echo "** unexpected option #$ac = '$argv[$ac]'"
-      exit 2
-
-   endif
-   @ ac += 1
+    else
+        echo "** unexpected option #$ac = '$argv[$ac]'"
+        goto BAD_EXIT
+        
+    endif
+    @ ac += 1
 end
 
 
@@ -146,7 +183,7 @@ set check = `3dinfo "$anat_inp"`
 echo "$#check"
 if ( "$#check" == "0" ) then
     echo "** ERROR: can't find inset file $anat_inp !"
-    goto EXIT
+    goto BAD_EXIT
 endif
 
 set inp_ORIENT = `3dinfo -orient "$anat_inp"`
@@ -157,7 +194,7 @@ set inp_VIEW  = "$inp_VIEW:gas/+//"
 set check = `3dinfo "$anat_ref"`
 if ( $#check == "0" ) then
     echo "** ERROR: can't find refset file $anat_ref !"
-    goto EXIT
+    goto BAD_EXIT
 endif
 
 # ========================= output/working dir ==========================
@@ -189,9 +226,7 @@ if ( ! -e $wdir ) then
 else
     echo "+* WARNING: Somehow found a premade working directory (?):"
     echo "      $wdir"
-
 endif
-
 
 # =======================================================================
 # =========================== ** PROCESS ** =============================
@@ -201,6 +236,22 @@ echo "\n-----> STARTING ---->"
 
 echo "\n\nThis command:"
 echo "$this_prog $argv\n\n"
+
+if ( $cmd_file == "" ) then
+    set cmd_file = "imqc_axize_${outpref}.txt"
+endif
+
+# copy original command:
+# dump copy of command into workdir/..
+if ( $output_cmd == 1 ) then
+    echo "++ Echoing the command to: $cmd_file"
+
+    echo "# Executed from the directory location:"  > $cmd_file
+    echo "# $here\n"            >> $cmd_file
+    echo "# The command was:"   >> $cmd_file
+    echo "# $this_prog $argv"   >> $cmd_file
+    echo "\n"                   >> $cmd_file
+endif
 
 echo "\nThe reference template is: $anat_ref"
 
@@ -225,8 +276,9 @@ set rout = "REF.nii.gz"
 # --------------------------------------------------------------
 
 # copy input file into working dir
+set iidx = `printf "%02d" $idx`
 set fin  = "$anat_inp"
-set fout = "${tpref}_${idx}.nii.gz"
+set fout = "${tpref}_${iidx}.nii.gz"
 set inp0 = $fout
 3dcalc    -echo_edu          \
     -a "$fin"                \
@@ -244,8 +296,9 @@ cd $wdir
 if ( $DoAni ) then
 
     echo "++ Doing a little anisosmoothing."
+    set iidx = `printf "%02d" $idx`
     set fin  = "$fout"
-    set fout = "${tpref}_${idx}_ani.nii.gz"
+    set fout = "${tpref}_${iidx}_ani.nii.gz"
     3danisosmooth -echo_edu       \
         -overwrite                \
         -iters 2                  \
@@ -254,12 +307,15 @@ if ( $DoAni ) then
         "$fin"
     @ idx += 1
 
-    set meanz = `3dROIstats -quiet -nzmean -mask "3dcalc( -a $fout -expr step(a) )" $fout`
+    set meanz = `3dROIstats -quiet -nzmean                  \
+                  -mask "3dcalc( -a $fout -expr step(a) )"  \
+                  $fout`
     set mval = $meanz[1]
     echo "++ Mean here is: $mval"
 
+    set iidx = `printf "%02d" $idx`
     set fin  = "$fout"
-    set fout = "${tpref}_${idx}_pos.nii.gz"
+    set fout = "${tpref}_${iidx}_pos.nii.gz"
     3dcalc -echo_edu                 \
         -a $fin                      \
         -expr "(step(a)*(a/$mval)**${powcon})" \
@@ -274,8 +330,9 @@ set v1 = `3dBrickStat -automask -percentile $valthr 1 $valthr "$fout"`
 set thr_t1 = "${v1[2]}"
 echo "\n\n++ Percentile for thresholding: ${thr_t1}\n"
 
+set iidx = `printf "%02d" $idx`
 set fin  = "$fout"
-set fout = "${tpref}_${idx}_thr.nii.gz"
+set fout = "${tpref}_${iidx}_thr.nii.gz"
 3dcalc    -echo_edu                               \
     -a      "$fin"                                \
     -expr   "maxbelow(${thr_t1},a)"               \
@@ -290,10 +347,10 @@ if ( $DoUni ) then
 
     echo "\n++ Doing unifizing."
 
-
     # unifize input
+    set iidx = `printf "%02d" $idx`
     set fin  = "$fout"
-    set fout = "${tpref}_${idx}_uni.nii.gz"
+    set fout = "${tpref}_${iidx}_uni.nii.gz"
     3dUnifize  -echo_edu         \
         -echo_edu                \
         -GM                      \
@@ -309,18 +366,18 @@ if ( $DoUni ) then
     set thr_t1 = "${v1[2]}"
     echo "\n\n++ Percentile for thresholding: ${thr_t1}\n"
 
+    set iidx = `printf "%02d" $idx`
     set fin  = "$fout"
-    set fout = "${tpref}_${idx}_thr2.nii.gz"
+    set fout = "${tpref}_${iidx}_thr2.nii.gz"
     3dcalc -echo_edu                           \
         -a        "$fin"                       \
         -expr     "maxbelow(${thr_t1},a)"      \
         -prefix   "$fout"                      \
         -overwrite
     @ idx += 1
-else
 
+else
     echo "\n++ NOT doing unifizing, at user behest."
-    
 endif
 
 # --------------------------------------------------------------
@@ -329,8 +386,9 @@ endif
 
 if ( $PRE_LR ) then
 
+    set iidx = `printf "%02d" $idx`
     set fin   = "$fout"
-    set fflip = "${tpref}_${idx}_LRflip.nii.gz"
+    set fflip = "${tpref}_${iidx}_LRflip.nii.gz"
     3dLRflip                         \
         -LR                          \
         -prefix $fflip               \
@@ -338,7 +396,8 @@ if ( $PRE_LR ) then
         $fin
     @ idx += 1
 
-    set ffout = "${tpref}_${idx}_LR6.nii.gz"
+    set iidx = `printf "%02d" $idx`
+    set ffout = "${tpref}_${iidx}_LR6.nii.gz"
     3dAllineate   -echo_edu               \
         -1Dmatrix_save _map_lr6           \
         -warp shift_rotate                \
@@ -359,7 +418,8 @@ if ( $PRE_LR ) then
 
     cat_matvec -ONELINE _map_lr6.aff12.1D -S > _map_lr_half.aff12.1D
 
-    set fout = "${tpref}_${idx}_LRmid.nii.gz"
+    set iidx = `printf "%02d" $idx`
+    set fout = "${tpref}_${iidx}_LRmid.nii.gz"
     3dAllineate   -echo_edu                    \
         -1Dmatrix_apply _map_lr_half.aff12.1D  \
         -prefix "$fout"                        \
@@ -370,8 +430,9 @@ if ( $PRE_LR ) then
 
     # update what is considered the 'base input' now for applying
     # final rot; won't use this one for further matching at the moment
+    set iidx = `printf "%02d" $idx`
     set fin  = $inp0
-    set fout2 = "${tpref}_${idx}_origLR.nii.gz"
+    set fout2 = "${tpref}_${iidx}_origLR.nii.gz"
     set inp0 = $fout2
     echo "++ New inp0 = $fout2"
     3dAllineate   -echo_edu                    \
@@ -388,8 +449,8 @@ endif
 
 if ( $OutMatchRef == "0" ) then
     # default
-
     echo "++ Aligning center of refset -> inset."
+
     # make data sets close together before starting to align formally;
     # rewrite REF
     @Align_Centers               \
@@ -398,7 +459,6 @@ if ( $OutMatchRef == "0" ) then
         -dset "$rout"            \
         -base "$fout"
 else
-
     echo "++ Aligning center of inset -> refset."
     @Align_Centers               \
         -cm                      \
@@ -414,18 +474,19 @@ endif
 
 # 9 DOF fit, inp -> ref; when we actually apply, won't include
 # scaling.
+set iidx = `printf "%02d" $idx`
 set fin  = "$fout"
-set fout = "${tpref}_${idx}_alnd.nii.gz"
-3dAllineate   -echo_edu               \
-    -1Dparam_save _map_9dof           \
-    -warp shift_rotate_scale          \
-    -prefix "$fout"                   \
-    -base "$rout"                     \
-    -twopass                          \
-    -source_automask                  \
-    -cost $costfunc                   \
-    $extra_allin_inps                 \
-    -source "$fin" \
+set fout = "${tpref}_${iidx}_alnd.nii.gz"
+3dAllineate   -echo_edu                    \
+    -1Dparam_save _map_9dof                \
+    -warp shift_rotate_scale               \
+    -prefix "$fout"                        \
+    -base "$rout"                          \
+    -twopass                               \
+    -source_automask                       \
+    -cost $costfunc                        \
+    $extra_allin_inps                      \
+    -source "$fin"                         \
     -overwrite
 @ idx += 1
 
@@ -440,8 +501,9 @@ printf "$vals[1-6] 0 0 0 0 0 0\n" >> map_fake12dof.param.1D
 # --------------------------------------------------------------
 
 # apply just the shift+rotation to the original volume
+set iidx = `printf "%02d" $idx`
 set fin  = "$inp0"
-set fout = "${tpref}_${idx}_alnd0.nii.gz" 
+set fout = "${tpref}_${iidx}_alnd0.nii.gz" 
 3dAllineate   -echo_edu                    \
     -1Dparam_apply map_fake12dof.param.1D  \
     -prefix "$fout"                        \
@@ -451,22 +513,23 @@ set fout = "${tpref}_${idx}_alnd0.nii.gz"
     -overwrite
 @ idx += 1
 
-
 # --------------------------------------------------------------
 
 # Sep,2016
 if ( $POST_LR ) then
 
+    set iidx = `printf "%02d" $idx`
     set fin   = "$fout"
-    set fflip = "${tpref}_${idx}_LRflip.nii.gz"
+    set fflip = "${tpref}_${iidx}_LRflip.nii.gz"
     3dLRflip                         \
         -LR                          \
         -prefix $fflip               \
         -overwrite                   \
         $fin
     @ idx += 1
-
-    set ffout = "${tpref}_${idx}_LR6.nii.gz"
+    
+    set iidx = `printf "%02d" $idx`
+    set ffout = "${tpref}_${iidx}_LR6.nii.gz"
     3dAllineate   -echo_edu               \
         -1Dmatrix_save _mmap_lr6          \
         -warp shift_rotate                \
@@ -481,7 +544,8 @@ if ( $POST_LR ) then
 
     cat_matvec -ONELINE _mmap_lr6.aff12.1D -S > _mmap_lr_half.aff12.1D
 
-    set fout = "${tpref}_${idx}_LRmid.nii.gz"
+    set iidx = `printf "%02d" $idx`
+    set fout = "${tpref}_${iidx}_LRmid.nii.gz"
     3dAllineate   -echo_edu                    \
         -1Dmatrix_apply _mmap_lr_half.aff12.1D \
         -prefix "$fout"                        \
@@ -498,8 +562,8 @@ if ( $OutMatchRef == "0" ) then
     # output).
     echo "++ Setting (0, 0, 0) to the center of mass."
     3dCM -automask -set 0 0 0 $fout
-endif
 
+endif
 
 # DONE, just copy endprod out!
 set fin  = $fout
@@ -512,19 +576,28 @@ set fout = ../"${outpref}.nii.gz"
     -expr 'a'                 \
     -prefix $fout
 
-# copy original command:
+# ---------------------------- VIEWER ---------------------------------
 
-# dump copy of command into workdir
-if ( $output_cmd == "1" ) then
-    echo "Echoing the command to: $cmd_file"
+if ( $DO_VIEWER ) then
 
-    echo "Executed from the directory location:"  > $cmd_file
-    echo "$here"              >> $cmd_file
-    echo "\n"                 >> $cmd_file
-    echo "The command was:"   >> $cmd_file
-    echo "$this_prog $argv"   >> $cmd_file
-    echo "\n"                 >> $cmd_file
+    if( $qc_prefix == "" ) then
+        set vpref = ${outpref}_imqc_axiz
+    else
+        set vpref = $qc_prefix
+    endif
+    echo "++ Image prefix output: $vpref"
+
+    #echo "++ Output QC #1: final olay on (essentially) original refset."
+    echo "++ HERE: $PWD"
+    $my_viewer      -ulay $inp0                     \
+                    -prefix $vpref                  \
+                    -outdir ".."                    \
+                    -montx 3 -monty 3               \
+                    -set_xhairs MULTI               \
+                    -label_mode 1 -label_size 4
 endif
+
+# ---------------------------------------------------------------------
 
 cd ..
 
@@ -541,7 +614,7 @@ printf "\n     $PWD/$fout\n\n"
 
 cd $here
 
-goto EXIT
+goto GOOD_EXIT
 
 # ========================================================================
 # ========================================================================
@@ -709,12 +782,14 @@ cat << EOF
 -------------------------------------------------------------------------
 EOF
 
-    goto EXIT
+    goto GOOD_EXIT
 
 SHOW_VERSION:
    echo "version  $version (${rev_dat})"
-   goto EXIT
+   goto GOOD_EXIT
 
-# send everyone here, in case there is any cleanup to do
-EXIT:
-   exit
+BAD_EXIT:
+    exit 1
+
+GOOD_EXIT:
+    exit 0
