@afni_refacer_make_master_addendum: helpify, to the barest extent possible

diff --git a/src/scripts_install/@afni_refacer_make_master_addendum b/src/scripts_install/@afni_refacer_make_master_addendum
--- a/src/scripts_install/@afni_refacer_make_master_addendum
+++ b/src/scripts_install/@afni_refacer_make_master_addendum
@@ -1,5 +1,7 @@
 #!/bin/tcsh
 
+@global_parse `basename $0` "$*" ; if ($status) exit 0
+
 # This program is just a patch/add-on to the
 # "@afni_refacer_make_master" program.  It is not really meant for
 # general use.  Instead, it records the very practical/empirical steps
@@ -19,14 +21,56 @@
 set version   = "3.0";   set rev_dat   = "Apr 23, 2022"
 # [PT: 22 Apr 2022] updated to make a re/de-face volume that clips
 # away more.  might soon become the default
+#
+set version   = "3.1";   set rev_dat   = "Apr 26, 2022"
+# [PT] helpify, sliiiightly
 
-# ---------------------------------------------------------------------------
-# check for necessary input dsets
+# ============================================================================
+# defaults/inputs
 
 set all_idset = ( afni_refacer_MNIbmask10.nii.gz \
                   afni_refacer_shell.nii.gz      )
 
+# ============================================================================
+# read in + interpret cmd line opts
+
+# don't allow this functionality, because this program takes no
+# options to run (at present)
+###if ( $#argv == 0 ) goto SHOW_HELP
+
+set ac = 1
+while ( $ac <= $#argv )
+
+    if ( ("$argv[$ac]" == "-h" ) || ("$argv[$ac]" == "-help" )) then
+        goto SHOW_HELP
+    endif
+
+    if ( "$argv[$ac]" == "-ver" ) then
+        goto SHOW_VERSION
+    endif
+
+    # there really aren't any options to use here...
+
+    # -------------------------------------------------------
+
+    else
+        echo "** unexpected option #$ac = '$argv[$ac]'"
+        exit 2
+
+    endif
+    @ ac += 1
+end
+
+# ============================================================================
+# start working
+
+# check for necessary input dsets
+
 foreach idset ( ${all_idset} )
+    ### [PT] someday, perhaps switch to using @Find* here, instead of
+    ### demanding only local files
+    #set ipath = `@FindAfniDsetPath "${idset}"`
+    #if ( "${ipath}" == "" ) then
     if ( ! -e ${idset} ) then
         echo "** ERROR: missing dset: ${idset}"
         exit 1
@@ -255,4 +299,49 @@ echo "   afni_refacer_shell_sym_1.0.nii.gz"
 echo "   afni_refacer_shell_sym_2.0.nii.gz"
 echo ""
 
-exit 0
+goto GOOD_EXIT
+
+# =============================================================================
+# =============================================================================
+
+SHOW_VERSION:
+
+    echo "$version"
+
+    goto GOOD_EXIT
+
+# ---------------------------------- 
+
+SHOW_HELP:
+
+cat <<EOF
+
+This is an adjunct program.  It actually takes no command line
+arguments to run.
+
+written by PA Taylor, the nearly anonymous
+---------------------------------------------------------------------
+Options
+
+-help
+-ver
+
+EOF
+
+    goto GOOD_EXIT
+ 
+# ---------------------------------- 
+
+FAIL_MISSING_ARG:
+    echo "** missing parameter for option $argv[$ac]"
+    goto BAD_EXIT
+
+# ---------------------------------- 
+
+BAD_EXIT:
+    exit 1
+
+# ---------------------------------- 
+
+GOOD_EXIT:
+    exit 0
