animal_warper+

diff --git a/src/scripts_install/@animal_warper b/src/scripts_install/@animal_warper
--- a/src/scripts_install/@animal_warper
+++ b/src/scripts_install/@animal_warper
@@ -32,6 +32,9 @@ set align_type = "all"
 set ok_to_exist = "0"
 set template_followers = ()
 set seg_followers = ()
+set feature_option = ""
+set feature_size = ""
+set supersize = ""
 
 # process user options
 set ac = 1
@@ -106,7 +109,7 @@ while ($ac <= $#argv)
         endif             
     else if ("$argv[$ac]" == "-ok_to_exist") then
         set ok_to_exist = "1"
-    else if ("$argv[$ac]" == "-no_orig_surfaces") then
+    else if ("$argv[$ac]" == "-no_surfaces") then
         set make_orig_surfaces = "0"
     else if ("$argv[$ac]" == "-template_followers") then
         @ ac ++
@@ -148,6 +151,16 @@ while ($ac <= $#argv)
             echo "** missing dataset for option '-seg_followers'"
             exit 1
         endif
+    else if ("$argv[$ac]" == "-feature_size") then
+        @ ac ++
+        if ( $ac > $#argv ) then
+            echo "** missing parameter for option '-feature_size'"
+            exit 1
+        endif
+        set feature_size = $argv[$ac]
+        set feature_option =  "-feature size $feature_size"
+    else if ("$argv[$ac]" == "-supersize") then
+        set supersize = "-supersize"
     else
         echo "** unknown option $argv[$ac]"
         exit 1
@@ -171,7 +184,12 @@ endif
 if ($outdir == "") then
    set outdir = "./template_align"
 endif
-mkdir -p $outdir
+
+if (($ok_to_exist == 1) && (-f ${outdir})) then
+    echo "reusing ${outdir}"
+else
+   mkdir -p $outdir
+endif
 
 # set costs for alignment
 if ($cost == "") then
@@ -238,7 +256,9 @@ set dsetprefix = `basename $dsetprefix .nii`
 
 # input datasets may not be +orig
 # so match input view equivalent even for NIFTI
-set origview = `3dinfo -av_space $dset`
+set origview = `3dinfo -av_space $dset |tr -d +`
+set origspace = `3dinfo -space $dset`
+
 
 # if input dataset is NIFTI vs AFNI format
 set dset_nifti = `3dinfo -is_nifti $dset`
@@ -251,13 +271,26 @@ set dset_nifti = `3dinfo -is_nifti $dset`
 
 # copy from AFNI format or from uncompressed data
 if (($outdir != ".") || ($dset_nifti != "1") || ($dsetext == "")) then
-   3dcopy $dset ${outdir}/${dsetprefix}.nii.gz
+   if (($ok_to_exist == 1) && (-f ${outdir}/${dsetprefix}.nii.gz)) then
+      echo "reusing ${outdir}/${dsetprefix}.nii.gz"
+   else
+      3dcopy $dset ${outdir}/${dsetprefix}.nii.gz
+   endif 
 endif
 
 if ($outdir != ".") then
-   3dcopy $base $outdir/
+   if (($ok_to_exist == 1) && (-f ${outdir}/`basename $base`)) then
+      echo "reusing ${outdir}/$base"
+   else
+      3dcopy $base $outdir/
+   endif
+   
    if ($segset != "") then
-      3dcopy $segset $outdir/
+      if (($ok_to_exist == 1) && (-f ${outdir}/`basename $segset`)) then
+         echo "reusing ${outdir}/$segset"
+      else
+         3dcopy $segset $outdir/
+      endif 
    endif
 endif
 
@@ -267,6 +300,11 @@ set dset = ${dsetprefix}.nii.gz
 set finalmaster = $dset
 
 set origdsetprefix = $dsetprefix
+# get sform and qform codes for original dataset (NIFTI applicable only)
+#set origsform_code = `nifti_tool -disp_hdr -infiles $dset| grep sform_code`
+#set origsform_code = $origsform_code[4]
+#set origqform_code = `nifti_tool -disp_hdr -infiles $dset| grep qform_code`
+#set origqform_code = $origqform_code[4]
 
 # figure out short name for template to insert into output files
 if ($templatename == "") then
@@ -294,7 +332,7 @@ if ($segset != "") then
    # if a template prefix has been selected by user, use that
    # for segmentation name output too 
    if ($templatename != "") then
-      set segname = $templatename
+      set segname = "${templatename}_atlas"
    else
       echo $segset |grep D99
       if ($status == 0) then
@@ -306,7 +344,11 @@ if ($segset != "") then
 endif
 
 # put the center of the dataset on top of the center of the template
-@Align_Centers -base $base -dset $dset
+if (($ok_to_exist == "1") && (-f  ${dsetprefix}_shft.nii.gz)) then
+   echo "reusing center aligned  ${dsetprefix}_shft.nii.gz"
+else 
+   @Align_Centers -base $base -dset $dset -overwrite
+endif
 
 # keep a copy of the inverse translation too
 # (should just be negation of translation column)
@@ -332,7 +374,7 @@ if (($ok_to_exist == "1") && (-f  ${dsetprefix}_al2std_mat.aff12.1D)) then
 else 
    align_epi_anat.py -dset2 $dset -dset1 $base -overwrite -dset2to1 \
     -giant_move -suffix _al2std -dset1_strip None -dset2_strip None \
-    -cost $cost $rigidopt
+    -cost $cost $rigidopt $feature_option $supersize
     
    set baseview = `3dinfo -av_space $base` 
    # convert the affine aligned output to NIFTI
@@ -434,6 +476,9 @@ else
    3dNwarpApply -prefix ${origdsetprefix}_warp2std.nii.gz                      \
       -nwarp "${dsetprefix}_WARP.nii.gz ${dsetprefix}_al2std_mat.aff12.1D" \
       -source $dset -master $base
+   @snapshot_volreg ${origdsetprefix}_warp2std.nii.gz $base snap_dt_${origdsetprefix}
+   @snapshot_volreg $base ${origdsetprefix}_warp2std.nii.gz snap_td_${origdsetprefix}
+
    
 #   rm -rf awpy_${dsetprefix}
 endif
@@ -465,6 +510,18 @@ else
    
    # put back in non-shifted version (really native space) 
    @Align_Centers -base ${finalmaster} -dset  ${templatename}_in_${origdsetprefix}.nii.gz -no_cp
+   # put back into the view of the original dataset to make it viewable in AFNI
+#   gunzip -f ${templatename}_in_${origdsetprefix}.nii.gz
+#   nifti_tool -mod_hdr -mod_field sform_code $origsform_code \
+#              -mod_field qform_code $origqform_code -overwrite \
+#              -infiles ${templatename}_in_${origdsetprefix}.nii
+#   gzip -f ${templatename}_in_${origdsetprefix}.nii
+   3drefit -space $origspace  ${templatename}_in_${origdsetprefix}.nii.gz 
+
+   @snapshot_volreg ${origdsetprefix}.nii.gz ${templatename}_in_${origdsetprefix}.nii.gz  \
+                    snap_dtorig_${origdsetprefix}
+   @snapshot_volreg ${templatename}_in_${origdsetprefix}.nii.gz ${origdsetprefix}.nii.gz  \
+                    snap_tdorig_${origdsetprefix}
 endif
 
 # process any template followers the same way
@@ -483,6 +540,13 @@ foreach temple_dset ($template_followers)
       
       # put back in non-shifted version (really native space) 
       @Align_Centers -base ${finalmaster} -dset  ${temple_prefix}_in_${origdsetprefix}.nii.gz -no_cp
+      # put back into the view of the original dataset to make it viewable in AFNI
+      #gunzip -f ${temple_prefix}_in_${origdsetprefix}.nii.gz
+      #nifti_tool -mod_hdr -mod_field sform_code $origsform_code \
+                 #-mod_field qform_code $origqform_code -overwrite \
+                 #-infiles ${temple_prefix}_in_${origdsetprefix}.nii
+      #gzip -f ${temple_prefix}_in_${origdsetprefix}.nii
+      3drefit -space $origspace ${temple_prefix}_in_${origdsetprefix}.nii.gz
   endif
 end
 
@@ -533,7 +597,7 @@ end
            # change the datum type to byte to save space if values range from 0 to 255
            # this step also gets removes the shift transform information in the header
            # overwriting original dataset just created
-           set segminmax = `3dBrickStat -min -max -slow $segm_dset`
+           set segminmax = `3dBrickStat -min -max -slow ${seg_prefix}_in_${origdsetprefix}.nii.gz`
            if (($segminmax[2] <= 255) && ($segminmax[1] >= 0)) then
               3dcalc -a ${seg_prefix}_in_${origdsetprefix}.nii.gz -expr a -datum byte -nscale \
               -overwrite -prefix ${seg_prefix}_in_${origdsetprefix}.nii.gz
@@ -541,8 +605,19 @@ end
            
            # copy segmentation information from atlas to this native-space
            #   segmentation dataset and mark to be shown with integer colormap
-           3drefit -cmap INT_CMAP ${seg_prefix}_in_${origdsetprefix}.nii.gz
+           #gunzip -f ${seg_prefix}_in_${origdsetprefix}.nii.gz
+           #nifti_tool -mod_hdr -mod_field sform_code $origsform_code \
+                 #-mod_field qform_code $origqform_code -overwrite \
+                 #-infiles ${seg_prefix}_in_${origdsetprefix}.nii
+           #gzip -f ${seg_prefix}_in_${origdsetprefix}.nii
+           3drefit -cmap INT_CMAP -space $origspace ${seg_prefix}_in_${origdsetprefix}.nii.gz
            3drefit -copytables $segm_dset ${seg_prefix}_in_${origdsetprefix}.nii.gz
+
+           @snapshot_volreg ${origdsetprefix}.nii.gz ${seg_prefix}_in_${origdsetprefix}.nii.gz  \
+                    snap_ds_orig_${seg_prefix}
+           @snapshot_volreg ${seg_prefix}_in_${origdsetprefix}.nii.gz ${origdsetprefix}.nii.gz  \
+                    snap_sd_orig_${seg_prefix}
+
            #mv ${segsetdir}/${segname}_in_${origdsetprefix}.nii.gz ./${segname}_in_${origdsetprefix}.nii.gz
        endif
     end 
@@ -564,7 +639,7 @@ end
        set baseperc = 15
        set basestats = `3dBrickStat -percentile $baseperc 1 $baseperc -non-zero \
            ${templatename}_in_${origdsetprefix}_aniso.nii.gz`
-       # count not right with percentile, so doing it separately here
+       # non-zero count not right with percentile, so doing it separately here
        set basestats2 = `3dBrickStat -max -count -non-zero \
            ${templatename}_in_${origdsetprefix}_aniso.nii.gz`
        set basethresh = $basestats[2] 
@@ -605,13 +680,9 @@ end
 
  endif
 
-cp $base ./
 
 # get rid of temporary warped datasets
 rm __tmp*_${dsetprefix}*.HEAD __tmp*_${dsetprefix}*.BRIK* __tmp*_${dsetprefix}*.1D
-rm ${dsetprefix}.1D
-rm ${dsetprefix}_inv.1D
-rm *_al2std_mat.aff12.1D
 
 exit 0
 
@@ -713,6 +784,10 @@ for all the atlas regions.
                          reverse warps for now. You may restart and reuse
                          existing warp transformations with the -ok_to_exist
                          option
+    -feature_size mm     Set size in mm for affine alignment. Use about 0.1
+                         for mouse, 0.5 for rat
+    -supersize           Allow for up to 50% size difference between subject
+                         and template
     -ok_to_exist         reuse and do not overwrite existing datasets.
                          This option is used for faster restarts or with
                          limited alignment options 
