@animal_warper: put in status checks through, exit by first failure

diff --git a/src/scripts_install/@animal_warper b/src/scripts_install/@animal_warper
--- a/src/scripts_install/@animal_warper
+++ b/src/scripts_install/@animal_warper
@@ -220,12 +220,16 @@ set progname = @animal_warper
 #      "*_shft*" datasets, so there should be full continuity with the
 #      help files and with the reported afni_proc.py usage.
 #    
-set version = "2.7" ; set date = "Oct 16, 2020"
+#set version = "2.7" ; set date = "Oct 16, 2020"
 # [PT] instead of early 3dcalc of src_dset0 to start things off, use
 # 3dresample there; with the concatenation of translations
 # (pshft+shft), we want to have (x,y,z) ordering of coords for the src
 # dset, and this ensures it.  Otherwise, get badness of something with
 # orient RSP, AIL, etc. is entered.
+#    
+set version = "2.8" ; set date = "Oct 16, 2020"
+# [PT] add status checks around, to stop in case of intermediate
+#      failure
 #    
 # --------------------------------------------------------------------
 # --------------------------------------------------------------------
@@ -857,6 +861,11 @@ else
      -prefix   "${outdir}/${src_dset}"
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (cp src)"
+    exit 1
+endif
+
 # -------------------- setup BASE dset
 
 # is the dataset somewhere else or current directory
@@ -904,6 +913,11 @@ else
    3dcopy "${base_dset}" ${outdir}/
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (copy base)"
+    exit 1
+endif
+
 # ------------------ copy atlas followers
 
 if ( ${#atlas_followers} != 0 ) then
@@ -915,6 +929,11 @@ if ( ${#atlas_followers} != 0 ) then
          # Use 3dcopy here to tables/atlas_points/subbrick labels wd
          # copy over
          3dcopy "${ff}" ${outdir}/
+     endif
+
+     if ( ${status} ) then
+        echo "** ERROR: program failed (copy atlas foll)"
+        exit 1
      endif
    end
 endif
@@ -1045,6 +1064,11 @@ if ( ($ok_to_exist == 1) && \
     echo "++ Moved old ${animal_outs} to: ${backup_ao}"
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (cp backup rep)"
+    exit 1
+endif
+
 # Set up output text file with file descriptions 
 echo "# List of inputs and outputs from @animal_warper" > ${animal_outs}
 
@@ -1137,6 +1161,11 @@ else
     endif
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (align centers)"
+    exit 1
+endif
+
 # *** After this point, the following files exist: 
 #          ${srcsh_dset} = src dset that has been shifted
 #          ${srcsh_shft} = text file of the shift itself
@@ -1149,6 +1178,11 @@ else
     cat_matvec                             \
           ${srcsh_shft} -I                 \
         > ${srcsh_shft_inv}
+endif
+
+if ( ${status} ) then
+    echo "** ERROR: program failed (al cent inv)"
+    exit 1
 endif
 
 printf "%-37s : %s\n"                   \
@@ -1188,6 +1222,11 @@ else
         -prefix ${srcsh_prefix}_al2std.nii.gz  \
         ${srcsh_prefix}_al2std${base_view}
 
+   if ( ${status} ) then
+       echo "** ERROR: program failed (AEA)"
+       exit 1
+   endif
+
    \rm ${srcsh_prefix}_al2std${base_view}.*
 endif
 
@@ -1222,6 +1261,11 @@ else
     cat_matvec -ONELINE                          \
         ${srcsh2_shft} -I                        \
         > ${srcsh2_shft_inv}
+
+    if ( ${status} ) then
+        echo "** ERROR: program failed (cat_matvec inv)"
+        exit 1
+    endif
 
     # THIS is the aff matrix that goes from shft2 to template space,
     # and what we should use later; it should have NO translation
@@ -1290,6 +1334,11 @@ else
         -source "${srcsh2_dset}"
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (3dAllineate)"
+    exit 1
+endif
+
 printf "%-37s : %s\n"                                      \
         "Input, aff-xformed to base"                       \
         "${srcsh2_prefix}_aff.nii.gz"                      \
@@ -1326,6 +1375,11 @@ cat_matvec -ONELINE                               \
     ${srcsh2_shft_inv}                            \
     ${srcsh2_prefix}_inv_al2std_mat.aff12.1D      \
     > ${src_abbrev}_composite_linear_to_template_inv.1D
+
+if ( ${status} ) then
+    echo "** ERROR: program failed (inv comp)"
+    exit 1
+endif
 
 printf "%-37s : %s\n"                                       \
         "Matrix, aff xform with shift"                      \
@@ -1410,6 +1464,11 @@ else
         ${srcsh2_prefix}_WARPINV.nii.gz
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (autowarp cp)"
+    exit 1
+endif
+
 # THIS is what should be given to afni_proc.py
 printf "%-37s : %s\n"                                           \
         "NL warp, aff2base"                                     \
@@ -1437,6 +1496,11 @@ else
         -warp1  "${srcsh2_prefix}_WARP.nii.gz"                     \
         -warp2  "${srcsh2_prefix}_al2std_mat.aff12.1D"             \
         -prefix "${srcsh2_prefix}_osh2base_WARP.nii.gz"
+endif
+
+if ( ${status} ) then
+    echo "** ERROR: program failed (3dNwarpCat)"
+    exit 1
 endif
 
 printf "%-37s : %s\n"                                             \
@@ -1467,6 +1531,11 @@ else
         -prefix "${srcsh2_prefix}_base2osh_WARP.nii.gz"
 endif
 
+if ( ${status} ) then
+    echo "** ERROR: program failed (3dNwarpCat 2)"
+    exit 1
+endif
+
 printf "%-37s : %s\n"                                             \
         "NL warp, base2osh (internal use)"                        \
         "${srcsh2_prefix}_base2osh_WARP.nii.gz"                   \
@@ -1492,6 +1561,11 @@ else
       -source "${srcsh2_dset}"                         \
       -master "${base_dset}"
 
+   if ( ${status} ) then
+       echo "** ERROR: program failed (3dNwarpApply)"
+       exit 1
+   endif
+
    # make masked version of orig dset in template space, using the
    # template itself.
    3dcalc -overwrite                                    \
@@ -1509,6 +1583,11 @@ else
       -Urad   30                                    \
       -input  ${src_abbrev}_warp2std_ns.nii.gz      \
       -prefix ${src_abbrev}_warp2std_nsu.nii.gz
+
+   if ( ${status} ) then
+       echo "** ERROR: program failed (3dUnifize)"
+       exit 1
+   endif
 
    # ... and put a note in its history, so that
    # gen_ss_review_scripts.py knows the name of the template
@@ -1630,9 +1709,14 @@ foreach ii ( `seq 1 1 ${#all_follow}` )
       3dNwarpApply  -overwrite                                       \
           -ainterp ${follow_interp}                                  \
           -prefix  ${follow_in_std}                                  \
-          -nwarp  "${srcsh2_prefix}_osh2base_WARP.nii.gz"             \
+          -nwarp  "${srcsh2_prefix}_osh2base_WARP.nii.gz"            \
           -source  tempfollow.nii.gz                                 \
           -master  "${base_dset}"
+
+      if ( ${status} ) then
+         echo "** ERROR: program failed (follower data, 1)"
+         exit 1
+      endif
 
       # keep propagating labels/atlases
       3drefit -copytables "${followset}" ${follow_in_std}
@@ -1666,6 +1750,12 @@ foreach ii ( `seq 1 1 ${#all_follow}` )
                # make these show up in AFNI as labeled ROI or atlas datasets 
                3drefit -copytables ${followset} ${follow_in_std}
                3drefit -cmap INT_CMAP ${follow_in_std}
+
+               if ( ${status} ) then
+                  echo "** ERROR: program failed (follower data, 2)"
+                  exit 1
+               endif
+
             endif
          endif
 
@@ -1726,6 +1816,11 @@ else
      -master ${srcsh2_dset}                                \
      -prefix ${templ_in_orig}
    
+   if ( ${status} ) then
+      echo "** ERROR: program failed (base2osh 1)"
+      exit 1
+   endif
+
    # put back in non-shifted version (really native space); default
    if (${center_out} == "native") then
       # Move center of dset with the INV of the original shift.  Funny
@@ -1735,6 +1830,12 @@ else
           -base ${src_dset}                           \
           -dset ${templ_in_orig}                      \
           -shift_xform_inv ${srcsh2_shft_inv}
+
+      if ( ${status} ) then
+         echo "** ERROR: program failed (base2osh 2)"
+         exit 1
+      endif
+
    endif 
 
    # Return original dataset view (to view in AFNI)
@@ -1768,6 +1869,11 @@ else
            -master ${srcsh2_prefix}.nii.gz                        \
            -prefix ${src_abbrev}_mask.nii.gz
 
+         if ( ${status} ) then
+            echo "** ERROR: program failed (base2osh brainmask)"
+            exit 1
+         endif
+
          # put back in non-shifted version (really native space);
          # default
          if (${center_out} == "native") then
@@ -1777,6 +1883,12 @@ else
                 -base ${src_dset}                     \
                 -dset ${src_abbrev}_mask.nii.gz      \
                 -shift_xform_inv ${srcsh2_shft_inv}
+
+            if ( ${status} ) then
+               echo "** ERROR: program failed (base2osh brainmask 2)"
+               exit 1
+            endif
+
          endif
 
          # Return original dataset view (to view in AFNI)
@@ -1797,6 +1909,12 @@ else
          -inputs __tmp_orig_mskd.nii.gz          \
          -prefix ${src_abbrev}_mask.nii.gz   \
          -overwrite
+
+      if ( ${status} ) then
+         echo "** ERROR: program failed (base2osh brainmask 3)"
+         exit 1
+      endif
+
    endif
 
    3dcalc \
@@ -1805,6 +1923,11 @@ else
       -expr 'a*step(b)'                       \
       -prefix ${src_abbrev}_ns.nii.gz     \
       -overwrite
+
+   if ( ${status} ) then
+      echo "** ERROR: program failed (base2osh brainmask 4)"
+      exit 1
+   endif
 
    # Image   : [ulay] edges of warped template; [olay] orig dset
    set ulay  = "${templ_in_orig}"
@@ -1885,6 +2008,11 @@ else
       -prefix ${src_abbrev}_nsu.nii.gz
 endif
 
+if ( ${status} ) then
+   echo "** ERROR: program failed (nsu)"
+   exit 1
+endif
+
 printf "%-37s : %s\n"                     \
         "Input (orig), no skull, uni"     \
         "${src_abbrev}_nsu.nii.gz"        \
@@ -1915,6 +2043,11 @@ foreach ii ( `seq 1 1 ${#template_followers}` )
         -master ${srcsh2_dset}                                 \
         -prefix ${template_in_orig}
       
+      if ( ${status} ) then
+         echo "** ERROR: program failed (base2osh template foll)"
+         exit 1
+      endif
+
       # put back in non-shifted version (really native space) 
       if (${center_out} == "native") then
         @Align_Centers                                         \
@@ -2005,6 +2138,11 @@ foreach ii ( `seq 1 1 ${#all_tfollow}` )
           -master ${srcsh2_dset}                           \
           -prefix ${segm_in_orig}
    
+       if ( ${status} ) then
+          echo "** ERROR: program failed (base2osh atl/seg foll)"
+          exit 1
+       endif
+
        # put back in non-shifted version (really native space) 
        if ($center_out == "native") then
           @Align_Centers                                          \
@@ -2030,12 +2168,17 @@ foreach ii ( `seq 1 1 ${#all_tfollow}` )
             -datum  byte                                          \
             -nscale                                               \
             -prefix ${segm_in_orig}
+
+          if ( ${status} ) then
+             echo "** ERROR: program failed (base2osh atl/seg foll, calc)"
+             exit 1
+          endif
+
        endif
 
       # keep propagating labels/atlases
       3drefit -copytables "${segm_dset}" ${segm_in_orig}
       3drefit -cmap INT_CMAP             ${segm_in_orig}
-
 
        # modal smoothing
        if ( "${modesmooth}" != "0") then
@@ -2059,6 +2202,12 @@ foreach ii ( `seq 1 1 ${#all_tfollow}` )
                   -input      ${segm_in_orig_pre}                        \
                   -prefix     ${segm_in_orig}                            \
                   -modesmooth ${modesmooth} 
+
+             if ( ${status} ) then
+                echo "** ERROR: program failed (base2osh atl/seg foll, @dj)"
+                exit 1
+             endif
+
           else
              # Standard modal smoothing (*no* replacement)
              3dLocalstat -overwrite                                      \
@@ -2066,6 +2215,11 @@ foreach ii ( `seq 1 1 ${#all_tfollow}` )
                   -nbhd   "SPHERE(-${modesmooth})"                       \
                   -prefix ${segm_in_orig}                                \
                   ${segm_in_orig_pre}
+
+             if ( ${status} ) then
+                echo "** ERROR: program failed (base2osh atl/seg foll, loc)"
+                exit 1
+             endif
 
              # make these show up in AFNI as labeled ROI or atlas datasets 
              3drefit                      \
@@ -2197,6 +2351,11 @@ foreach ii ( `seq 1 1 ${#all_tfollow}` )
 
            # ------- isosurfs in native space: only for ATLAS followers
 
+           if ( ${status} ) then
+              echo "** ERROR: program failed (base2osh atl/seg foll, table)"
+              exit 1
+           endif
+
            if ( ( $make_orig_surfaces == "1" ) && \
                 ( -f ${segm_in_orig} ) ) then
 
@@ -2262,6 +2421,10 @@ if ( $make_orig_surfaces == "1" ) then
         ${templ_in_orig}
    endif
 
+   if ( ${status} ) then
+      echo "** WARNING: program failed (templ surf, anisosmoo)"
+   endif
+
    # also remove any  small clusters for surface generation
    #  (threshold here is specific so may need tweaking)
    set baseperc   = 15
@@ -2293,6 +2456,10 @@ if ( $make_orig_surfaces == "1" ) then
         -clust_nvox  ${minbrainvolume}
    endif
 
+   if ( ${status} ) then
+      echo "** WARNING: program failed (templ surf, clust)"
+   endif
+
    if ( ($ok_to_exist == "1") && \
         (-f  ${templ_in_origG} ) ) then
       echo "++ Reusing template in native space surface dataset"
@@ -2303,6 +2470,10 @@ if ( $make_orig_surfaces == "1" ) then
         -o        ${templ_in_origG}                          \
         -noxform                                             \
         -Tsmooth 0.01 6
+   endif
+
+   if ( ${status} ) then
+      echo "** WARNING: program failed (templ surf, isosurf)"
    endif
 
    printf "%-37s : %s\n"                                     \
