@animal_warper: -init_scale opt for very small/large inputs

diff --git a/src/scripts_install/@animal_warper b/src/scripts_install/@animal_warper
--- a/src/scripts_install/@animal_warper
+++ b/src/scripts_install/@animal_warper
@@ -342,9 +342,13 @@ set progname = @animal_warper
 #          + change Urad in 3dUnifize to 14, from 30 (latter seems 
 #            waaaay too large for most animal dsets?)
 #   
-set version   = "3.52";   set rev_dat   = "Oct 27, 2021"
+#set version   = "3.52";   set rev_dat   = "Oct 27, 2021"
 #     + [PT] fix desc of opt name "-qw_opts" in help to what it actually is:
 #            "-extra_qw_opts".  Thanks, C Garin.
+#   
+set version   = "3.6";   set rev_dat   = "Dec 1, 2022"
+#     + [PT] new opt '-init_scale ..' for pre-scaling input anatomical if
+#            it is much smaller/larger than the template (applied in AEA)
 #   
 # --------------------------------------------------------------------
 # --------------------------------------------------------------------
@@ -397,6 +401,10 @@ set all_known_dset_abbrev = ( )
 
 set DO_ALIGN_CENTERS   = 1
 set align_centers_meth = "-grid" 
+
+set DO_INIT_SCALE      = 0           # [PT: Dec 1, 2022] overcome size mismatch
+set init_scale         = 1.0
+set opt_init_scale     = ""
 
 set feature_size       = "0.5"       # [PT: Dec 22, 2020] new default
 set feature_option     = "-feature_size $feature_size"
@@ -602,6 +610,16 @@ while ($ac <= $#argv)
             exit 1
         endif
         set maxlev =  $argv[$ac]
+
+    else if ("$argv[$ac]" == "-init_scale") then
+        set this_opt = "$argv[$ac]"
+        @ ac ++
+        if ( $ac > $#argv ) then
+            echo "** missing parameter for option '${this_opt}'"
+            exit 1
+        endif
+        set init_scale    = $argv[$ac]
+        set DO_INIT_SCALE = 1
 
     else if ("$argv[$ac]" == "-align_type") then
         set this_opt = "$argv[$ac]"
@@ -1458,7 +1476,19 @@ if ( ( $ok_to_exist == "1" ) && \
    echo "++ Reusing affine transformation matrix"
 else
 
-   set aaa = ( -giant_move )
+   #set aaa = ( -giant_move )
+
+   if ( $DO_INIT_SCALE ) then
+      echo "++ Make pre_matrix for initial scale: ${init_scale}"
+
+      set premat_fname   = "${imed}/aea_pre_matrix.1D"
+      set opt_init_scale = "-pre_matrix ${premat_fname}"
+cat <<EOF > "${premat_fname}"
+${init_scale} 0.0 0.0 0.0
+0.0 ${init_scale} 0.0 0.0
+0.0 0.0 ${init_scale} 0.0
+EOF
+   endif
 
    # outputs a BRIK/HEAD file
    # [PT: July 8, 2021] allow '-giant_move' to be switched to other opts
@@ -1473,7 +1503,7 @@ else
     -dset1_strip  None                                              \
     -dset2_strip  None                                              \
     -cost $cost $rigidopt $feature_option $supersize ${aff_move}    \
-    -master_dset2  BASE
+    -master_dset2  BASE   ${opt_init_scale}
 
    if ( ${status} ) then
        echo "** ERROR: program failed (AEA)"
@@ -3226,6 +3256,13 @@ Options ~1~
 
   -supersize          :allow for up to 50% size difference between subject
                        and template
+
+  -init_scale  IS     :useful if the input dset is much larger or smaller
+                       than the reference template.  'IS' is the approximate
+                       length ratio of the input to the template.  So, if 
+                       you align a baby shark (doo doo, doo doo doo doo) 
+                       brain to an adult shark template brain, you might 
+                       use this option with a value of 0.75, for example.
 
   -mode_smooth_size n :modal smoothing kernel size in voxels (not mm)
                        This determines the size of a spatial regularization
