@chauffeur:back to xvfb basics

diff --git a/src/scripts_install/@chauffeur_afni b/src/scripts_install/@chauffeur_afni
--- a/src/scripts_install/@chauffeur_afni
+++ b/src/scripts_install/@chauffeur_afni
@@ -38,8 +38,11 @@
 #     + xvfb-run: new option to set colordepth to 24, so opacity works
 #       in the AFNI commands
 # 
-set version   = "2.4";   set rev_dat   = "May 20, 2017"
+#set version   = "2.4";   set rev_dat   = "May 20, 2017"
 #     + more unique naming of tempdir; safer for cluster runs
+# 
+set version   = "2.5";   set rev_dat   = "June 1, 2017"
+#     + back to regular xvfb and Bob's search
 # 
 # =====================================================================
 
@@ -609,41 +612,41 @@ echo "\n------------------- end of optionizing -------------------\n"
 
 ########## NB: D. Godlove suggests this unnecessary, using instead
 ##########     `xvfb-run -a ...` below for afni command.
-# # start the X virtual frame buffer on display #xdisplay, a la bob
-# 
-# set ranval = `count -dig 1 1 999999 R1`
-# 
-# if( $?xdisplay == 0 )then
-#   set killX     = 1
-#   set ntry      = 1
-#   set Xnotfound = 1
-#   while( $Xnotfound )
-#     set xdisplay = `count -dig 1 3 999 R1`
-#     if( -e /tmp/.X${xdisplay}-lock ) continue
-#     echo " -- trying to start Xvfb :${xdisplay}"
-#     Xvfb :${xdisplay} -screen 0 1024x768x24 &
-#     sleep 1
-#     jobs > zzerm.$ranval.txt
-#     grep -q Xvfb zzerm.$ranval.txt
-#     set Xnotfound = $status
-#     \rm -f zzerm.$ranval.txt
-#     if( $Xnotfound == 0 )break ;
-#     @ ntry++
-#     if( $ntry > 99 )then
-#       echo "** ERROR: can't start Xvfb -- exiting"
-#       goto BAD_EXIT
-#     endif
-#   end
-# endif
-# 
-# setenv DISPLAY :${xdisplay}
+# start the X virtual frame buffer on display #xdisplay, a la bob
+
+set ranval = `count -dig 1 1 999999 R1`
+
+if( $?xdisplay == 0 )then
+  set killX     = 1
+  set ntry      = 1
+  set Xnotfound = 1
+  while( $Xnotfound )
+    set xdisplay = `count -dig 1 3 999 R1`
+    if( -e /tmp/.X${xdisplay}-lock ) continue
+    echo " -- trying to start Xvfb :${xdisplay}"
+    Xvfb :${xdisplay} -screen 0 1024x768x24 &
+    sleep 1
+    jobs > zzerm.$ranval.txt
+    grep -q Xvfb zzerm.$ranval.txt
+    set Xnotfound = $status
+    \rm -f zzerm.$ranval.txt
+    if( $Xnotfound == 0 )break ;
+    @ ntry++
+    if( $ntry > 99 )then
+      echo "** ERROR: can't start Xvfb -- exiting"
+      goto BAD_EXIT
+    endif
+  end
+endif
+
+setenv DISPLAY :${xdisplay}
 set OW = "OPEN_WINDOW"
 
 # -------------------------------------------------------------------
 # ---------------- The actual, driven command! ----------------------
 
-xvfb-run --server-args="-screen 0 1024x768x24" -a  \
-    afni -noplugins -no_detach  -echo_edu                           \
+#xvfb-run -d --server-args="-screen 0 1024x768x24" -w 0  \
+afni -noplugins -no_detach  -echo_edu                           \
      -com "SWITCH_UNDERLAY ${read_ulay}"                            \
      -com "SWITCH_OVERLAY  ${read_olay}"                            \
      -com "SET_PBAR_ALL    ${pbar_sign}${ncolors} $topval $my_cbar" \
