@emo -reject_midk

diff --git a/src/scripts_install/@extract_meica_ortvec b/src/scripts_install/@extract_meica_ortvec
--- a/src/scripts_install/@extract_meica_ortvec
+++ b/src/scripts_install/@extract_meica_ortvec
@@ -17,6 +17,7 @@ modification history for $prog :
            - remove entries that are duplicated across either
              rejected/midk-rejected or accepted/ignored
            - Thanks to L Dowdle for noting the problem.
+   0.4   8 Apr 2019 : add -reject_midk and -reject_ignored
 
 EOF
 exit
@@ -24,7 +25,7 @@ POSTHIST:
 
 # ----------------------------------------------------------------------
 # init vars
-set VERSION = "0.3  May 24, 2018"
+set VERSION = "0.4  April 8, 2019"
 set prog = `basename $0`
 
 # ----------------------------------------------------------------------
@@ -33,6 +34,10 @@ set verb = 1
 set meicadir = .
 set workdir = regwork
 set prefix = meica_bad_ort.1D
+
+# rejection preferences
+set rej_mid = 1         # reject midk reject
+set rej_ign = 0         # keep 'ignore'
 
 
 # ----------------------------------------------------------------------
@@ -65,6 +70,30 @@ while ( $ac <= $#argv )
          exit 1
       endif
       set prefix = $argv[$ac]
+
+   else if ( "$argv[$ac]" == "-reject_ignored" ) then
+      @ ac ++
+      if ( $ac > $#argv ) then
+         echo "** missing parameter for option '-reject_ignored'"
+         exit 1
+      endif
+      set rej_ign = $argv[$ac]
+      if ( $rej_ign != 0 && $rej_ign != 1 ) then
+         echo "** -reject_ignored: takes either 0 or 1 as a parameter"
+         exit 1
+      endif
+
+   else if ( "$argv[$ac]" == "-reject_midk" ) then
+      @ ac ++
+      if ( $ac > $#argv ) then
+         echo "** missing parameter for option '-reject_midk'"
+         exit 1
+      endif
+      set rej_mid = $argv[$ac]
+      if ( $rej_mid != 0 && $rej_mid != 1 ) then
+         echo "** -reject_midk: takes either 0 or 1 as a parameter"
+         exit 1
+      endif
 
    else if ( "$argv[$ac]" == "-work_dir" ) then
       @ ac ++
@@ -101,10 +130,6 @@ set mfin_ignore = $meicadir/comp_table.txt
 
 # all meica components
 set meica_comp_file = $meicadir/meica_mix.1D
-
-# rejection preferences
-set rej_mid = 1         # reject midk reject
-set rej_ign = 0         # keep 'ignore'
 
 # ----------------------------------------------------------------------
 # check on the state of things, and try to make an echo list
@@ -249,10 +274,16 @@ cat << EOF
 
    options:
 
-      -prefix    PREFIX         : name for output 1D ortvec file
-      -meica_dir MDIR           : directory for meica files
-      -work_dir  WDIR           : sub-directory for work
-      -verb      VLEVEL         : set verbosity level
+      -prefix         PREFIX    : name for output 1D ortvec file
+      -meica_dir      MDIR      : directory for meica files
+      -reject_ignored VAL       : VAL=0/1, do we reject ignored components
+                                  (default = 0, keep, do not reject)
+                                  (should probably never reject)
+      -reject_midk    VAL       : VAL=0/1, do we reject midk components
+                                  (default = 1, reject)
+                                  (should probably default to keeping)
+      -work_dir       WDIR      : sub-directory for work
+      -verb           VLEVEL    : set verbosity level
 
    
    More options will be added, but this is enough to get used by
