tweak 3dGrayplot and AFNI SUMA line colors

diff --git a/src/scripts_install/@grayplot b/src/scripts_install/@grayplot
--- a/src/scripts_install/@grayplot
+++ b/src/scripts_install/@grayplot
@@ -1,5 +1,7 @@
 #!/bin/tcsh
 
+# Help the pitiful luser?
+
 set do_help = 0
 if( $#argv == 0 ) set do_help = 1
 if( $do_help == 0 )then
@@ -9,14 +11,17 @@ if( $do_help )then
   echo "Usage: @grayplot [OPTIONS] dirname"
   echo
   echo "Script to read files from an afni_proc.py results directory"
-  echo "and produce a grayplot from the errts dataset, combined with"
+  echo "and produce a grayplot from the errts dataset(s), combined with"
   echo "a motion magnitude indicator graph."
   echo
   echo "Will produce a plot for errts.SUBJECT+tlrc and for"
   echo "errts.SUBJECT_REML+tlrc, if both datasets were computed."
   echo "And errts.SUBJECT_REMLwh+tlrc will also be plotted, if option"
   echo "'-regress_opts_reml -Rwherr errts.SUBJECT_REMLwh' was given"
-  echo "to afni_proc.py -- this is the 'pre-whitened' residuals dataset."
+  echo "to afni_proc.py -- this is the 'pre-whitened' residuals dataset,"
+  echo "Which is the noise examplar from which the 3dREMLfit statistics"
+  echo "are computed."
+  echo
   echo "The output images are grayscale, stored in .png format, and"
   echo "have names like 'Grayplot.errts.SUBJECT.ORDERMETH.png'."
   echo "* See the OPTIONS section below for the ordering methods"
@@ -61,30 +66,64 @@ if( $do_help )then
   echo "      operations are needed to reach a given voxel; that is, how"
   echo "      far a voxel is from the partition's boundary. Voxels at the"
   echo "      edge of the partition are first, etc."
-  echo "  The default (no option given) order is simple coordinate order"
-  echo "  in the dataset, which may not be very interesting."
+  echo "    -ijkorder ="
+  echo "      Within each partition, voxels are just ordered by the 3D index"
+  echo "      in which they appear in the dataset. Possibly not exciting."
+  echo "      This order will primarily be from Inferior to Superior in the"
+  echo "      brain (top to bottom in the grayplot image), using AFNI's"
+  echo "      convention for storing +tlrc datasets."
+  echo "  The default (no option given) order is '-ijkorder'."
   echo
-  echo "Author: RWCox -- May 2018"
-  echo "Notice: Subject to drastic change at any instant"
+  echo "NOTA BENE:"
+  echo "* Also see '3dGrayplot -help', since the actual grayplot is created"
+  echo "  by that program."
+  echo "* Since the vertical (spatial) dimension of the output grayplot image"
+  echo "  is 500 pixels, each horizontal (time) row in the plot will be"
+  echo "  the combination of multiple voxels, in whatever order they appear."
+  echo "* Since the horizontal dimension of the output grayplot image is"
+  echo "  1000 pixels, unless the time series has more than 1000 points, each"
+  echo "  time point will be stretched to fill more than one pixel."
+  echo "* I personally find '-pvorder' to be the most useful, but the"
+  echo "  other orderings can also be interesting to compare."
+  echo "* I like to use the AFNI 'aiv' program to view the images, rather than"
+  echo "  a standard image viewer program, since aiv's default settings show"
+  echo "  more contrast, which helps me see more structure in the grayplots."
+  echo "* Note that 'structure' in the grayplots of the errts datasets is"
+  echo "  in some sense BAD, since individual-subject statistics are computed"
+  echo "  from the errts dataset assuming it is just noise."
+  echo "* I prefer using 3dREMLfit and so the most relevant grayplot is from"
+  echo "  errts.SUBJECT_REMLwh+tlrc (the pre-whitened errts.SUBJECT_REML+tlrc)."
+  echo "  The voxelwise pre-whitening tends to removes a little of the visible"
+  echo "  structure in the grayplot."
+  echo "* Author: RWCox -- May 2018"
+  echo "* Notice: Subject to drastic change at any instant."
   exit 0
 endif
 
-set order = " "
-set osuff = "XYZORDER.png"
+# set defaults
+
+set order = "-ijkorder"
+set osuff = "IJKORDER.png"
 set ddir  = "."
 set iarg  = 0
+
+# check command line args
 
 if( $#argv > 0 )then
   set iarg = 1
   if( "$argv[$iarg]" == "-peelorder" )then
     set order = "-peelorder" ; set osuff = "PEELORDER.png" ; @ iarg ++
   else if( "$argv[$iarg]" == "-pvorder" )then
-    set order = "-pvorder" ; set osuff = "PVORDER.png" ; @ iarg ++
+    set order = "-pvorder"   ; set osuff = "PVORDER.png"   ; @ iarg ++
+  else if( "$argv[$iarg]" == "-ijkorder" )then
+    set order = "-ijkorder"  ; set osuff = "IJKORDER.png"  ; @ iarg ++
   endif
   if( $#argv >= $iarg )then
     set ddir = $argv[$iarg] ; @ iarg ++
   endif
 endif
+
+# switch to input/output directory
 
 pushd $ddir
 
@@ -92,7 +131,7 @@ pushd $ddir
 
 set aa = ( anat_final.*+tlrc.HEAD )
 if( $#aa != 1 )then
-  echo "Can't find anat_final.*+tlrc.HEAD" ; exit 1
+  echo "** ERROR @grayplot: Can't find anat_final.*+tlrc.HEAD" ; exit 1
 endif
 
 set subj = `echo $aa[1] | sed -e 's/+tlrc.HEAD//' -e 's/anat_final.//'`
@@ -103,7 +142,7 @@ set dmask = mask_epi_anat.${subj}+tlrc.HEAD
 if( ! -f $dmask )then
   set dmask = full_mask.${subj}+tlrc.HEAD
   if( ! -f $dmask )then
-    echo "** Can't find EPI mask :(" ; exit 1
+    echo "** ERROR @grayplot: Can't find EPI mask :(" ; exit 1
   endif
 endif
 
@@ -113,13 +152,16 @@ echo "----- Plotting motion"
 
 set dlist = ( dfile.r*.1D )
 set nrun  = $#dlist
+if( $nrun == 0 )then
+  echo "** ERROR @grayplot: Can't find motion parameters files" ; exit 1
+endif
 
 foreach ddd ( $dlist )
   1d_tool.py -infile $ddd -derivative -collapse_cols euclidean_norm \
              -write enorm.$ddd
 end
 
-# glue them together
+# glue results together into one file
 
 \rm -f enorm.dfile.all*
 cat enorm.dfile.r*.1D > enorm.dfile.allU.1D
@@ -178,25 +220,26 @@ else
   echo "----- Segmenting $aa[1]"
   3dSeg -anat $aa[1] -mask AUTO -blur_meth BIM -classes 'CSF; GM; WM'
   if( -f Segsy/Classes+tlrc.HEAD ) mv Segsy/Classes+tlrc.* .
-  \rm -rf Segsy
+  if( -d Segsy ) \rm -rf Segsy
 endif
 
 if( -f Classes+tlrc.HEAD )then
-# convert CSF=1 to CSF=4
+# convert CSF=1 to CSF=4 (so GM=2 WM=3 CSF=4 is the grayplot order)
   3dcalc -a Classes+tlrc.HEAD -expr 'ifelse(equals(a,1),4,a)' \
          -datum byte -nscale -prefix GmaskA.nii
 # convert from anat resolution to EPI resolution
   3dfractionize -template $dmask \
                 -input GmaskA.nii -prefix GmaskB.nii -vote
-# combine with EPI mask
+# intersect with EPI mask
   3dcalc -a GmaskB.nii -b $dmask -expr 'a*b' -prefix GmaskC.nii
   set ggg = GmaskC.nii
   \rm -rf GmaskA.nii GmaskB.nii
 else
+# if segmentation failed for some reason
   set ggg = $dmask
 endif
 
-# grayplot both errts files, if they both exist
+# grayplot diverse errts files
 
 set eaa = errts.${subj}+tlrc.HEAD
 set ebb = errts.${subj}_REML+tlrc.HEAD
@@ -212,7 +255,7 @@ foreach eee ( $eaa $ebb $ecc )
                -mask $ggg           \
                -input $eee          \
                -prefix G.errts.pgm
-# merge with graph
+# merge with graph image
     pnmcat -tb enorm.dfile.allC.ppm G.errts.pgm | \
       pnmtopng - > Grayplot.${ppp}.${osuff}
     echo " ---- Result in $cwd/Grayplot.${ppp}.${osuff}"
@@ -220,7 +263,7 @@ foreach eee ( $eaa $ebb $ecc )
   endif
 end
 
-# grayplot the all_runs file
+# grayplot the all_runs file for giggles
 
 @ port = 2 * $nrun
 
@@ -234,7 +277,7 @@ foreach eee ( all_runs.${subj}+tlrc.HEAD )
                -mask $ggg           \
                -input $eee          \
                -prefix G.errts.pgm
-# merge with graph
+# merge with graph image
     pnmcat -tb enorm.dfile.allU.ppm G.errts.pgm | \
       pnmtopng - > Grayplot.${ppp}.${osuff}
     echo " ---- Result in $cwd/Grayplot.${ppp}.${osuff}"
